apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-app
      component: worker
  template:
    metadata:
      labels:
        app: voting-app
        component: worker
    spec:
      containers:
      - name: worker
        image: kodekloud/examplevotingapp_worker
